### USERS ###

# getUsers
GET http://localhost:3001/api/users

###

# getSingleUser by Id
GET http://localhost:3001/api/users/63b3c9331f40d2bea85ecd00

### 

# createUser
POST http://localhost:3001/api/users
Content-Type:  application/json

{
  "userName": "testing123123",
  "email": "test123123@gmail.com"
}

###
# updateUser by Id
PUT http://localhost:3001/api/users

###

# deleteUsers by Id
DELETE http://localhost:3001/api/users/63b3ab461c613f6b236a9979

###

# addFriend 
PUT http://localhost:3001/api/users/63b46260c82293ec7356dc8f/friends/63b3c9331f40d2bea85eccfc

{
  "userName": "Chris",
  "email": "Chris@gmail.com"
}
###

# removeFriend
DELETE http://localhost:3001/api/users/63b46260c82293ec7356dc8f/friends/63b3c9331f40d2bea85eccfc

{
  "userName": "Chris",
  "email": "Chris@gmail.com"
}

###

### THOUGHTS ###

# getThought
GET http://localhost:3001/api/thoughts

###

# getSingleThought by Id
GET http://localhost:3001/api/thoughts/63b3c182a1c4e86477141f7d

### 

# createThought
POST http://localhost:3001/api/thoughts
Content-Type:  application/json

{
  "thoughtText": "Here's a cool thought...",
  "userName": "asdfasdfasdfasdfad",
  "userId": "63b3c0e0a1c4e86477141f5e"
}
###
# updateThought by Id
PUT http://localhost:3001/api/thoughts/

###

# deleteThoughts by Id
DELETE http://localhost:3001/api/thoughts/63b3c182a1c4e86477141f7d
