### USERS ###

# getUsers
GET http://localhost:3001/api/users

###

# getSingleUser by Id
GET http://localhost:3001/api/users/

### 

# createUser
POST http://localhost:3001/api/users


{
  "username": "lernantino",
  "email": "lernantino@gmail.com"
}
###
# updateUser by Id
PUT http://localhost:3001/api/users

###

# deleteUsers by Id
DELETE http://localhost:3001/api/users/

###

### THOUGHTS ###

# getThought
GET http://localhost:3001/api/thoughts

###

# getSingleThought by Id
GET http://localhost:3001/api/thoughts/

### 

# createThought
POST http://localhost:3001/api/thoughts


{
  "thoughtText": "Here's a cool thought...",
  "username": "lernantino",
  "userId": "5edff358a0fcb779aa7b118b"
}
###
# updateThought by Id
PUT http://localhost:3001/api/thoughts

###

# deleteThoughts by Id
DELETE http://localhost:3001/api/thoughts/
